spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5434/order-db
    username: order-user
    password: order-password
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

server:
  servlet:
    context-path: /api/v1
  port: 9020


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


#resilience4j:
#  retry:
#    instances:
#      inventoryRetry:
#        base-config: default
#        wait-duration:             # overriing the default config
#          seconds: 7
#    configs:
#      defaults :
#        max-attempts: 3
#        wait-duration:
#          seconds: 5
#
#  ratelimiter:
#    instances:
#      inventoryRateLimiter:
#        limit-for-period: 1
#        limit-refresh-period: 5s
#        timeout-duration: 1s
#
#  circuitbreaker:
#    instances:
#      inventoryFeignClient:
#        register-health-indicator: true            #exposes circuit breaker health via actuator
#        sliding-window-size: 10
#        failure-rate-threshold: 50
#        wait-duration-in-open-state:
#          seconds: 10
#        permitted-number-of-calls-in-half-open-state: 5
#        sliding-window-type: count_based
#        minimum-number-of-calls: 10
#        automatic-transition-from-open-to-half-open-enabled: true
#        event-consumer-buffer-size: 10


#actuator configuration
management:
#  health:
#    circuitbreakers:
#      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
